# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\")\n\x0b\x46ileRequest\x12\x11\n\x04type\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_type\"\x1d\n\x0c\x46ile><x46ileResponse\x12\r\n\x05\x66iles\x18\x01 \x01(\t2.\n\x07GetFile\x12#\n\x04List\x12\x0c.FileRequest\x1a\r.FileResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILEREQUEST._serialized_start=17
  _FILEREQUEST._serialized_end=58
  _FILERESPONSE._serialized_start=60
  _FILERESPONSE._serialized_end=89
  _GETFILE._serialized_start=91
  _GETFILE._serialized_end=137
# @@protoc_insertion_point(module_scope)