version: '3.1'
services:
  moodle:
    image: bitnami/moodle:4.1.2
    container_name: moodle
    restart: always
    environment:
      MOODLE_DATABASE_TYPE: mysqli
      MOODLE_DATABASE_HOST: 10.73.128.3
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_USER: root
      MOODLE_DATABASE_NAME: bitnami_moodle
      MOODLE_DATABASE_PASSWORD: 12345
      MOODLE_USERNAME: user
      MOODLE_PASSWORD: root
      MOODLE_SKIP_BOOTSTRAP: "yes"
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - $HOME/mnt/moodle:/bitnami{
    env_file:
      "env_file.txt"
