version: '3.1'
services:
  moodle:
    image: bitnami/moodle:4.1.2
    container_name: moodle
    restart: always
    environment:
      MOODLE_DATABASE_TYPE: mysqli
      MOODLE_DATABASE_HOST: ${DB_HOST}
      MOODLE_DATABASE_PORT_NUMBER: ${DB_PORT}
      MOODLE_DATABASE_USER: ${DB_USER}
      MOODLE_DATABASE_NAME: ${DB_NAME}
      MOODLE_DATABASE_PASSWORD: ${DB_PASS}
      MOODLE_USERNAME: user
      MOODLE_PASSWORD: root
      MOODLE_SKIP_BOOTSTRAP: "yes"
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - $HOME/mnt/moodle:/bitnami
    env_file:
      - ./env_file.txt
